<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>LoloMinecraftLauncher</AssemblyName>
    <RootNamespace>LoloMinecraftLauncher</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="gui\**" />
    <EmbeddedResource Remove="gui\**" />
    <None Remove="gui\**" />
    <Page Remove="gui\**" />
  </ItemGroup>
</Project>
